services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    stdin_open: true
    build:
      contest: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    comman: ["npm", "run", "test"]